### ISSUE TITLE
Spec

### ISSUE THREAD

**Issue by simonwheatley** [cftp/decision-trees#1]
Decision trees will be a plugin which allows a user to create one or more branched (dendritic) decision trees from the WordPress admin area. A decision tree will consist of two or more nodes which each explain a question or item which requires a decision. Each node will have a number of one way paths from it to other nodes, I am referring to these as "answers".

This diagram from Wikipedia illustrates the kind of decision trees this plugin will handle. Note the simple branching structure, and that all nodes only link to their own child nodes, and there is no "doubling back" or "linking across". I hope this will keep a good level of simplicity, and help users to maintain a coherent mental model of each tree.

![File:Investment_decision_Insight](https://f.cloud.github.com/assets/233434/176365/6d179a38-7b71-11e2-8125-f63e719bcd31.png)

The plugin will register a CPT called "Decision Trees".

**Editing**

Required elements of a node:
- A title
- At least one answer

Initially we will just require multiple choice answers, which could be implemented as an array of links (most probably), or an array of radio buttons (I'm not sure why [Smart Answers](digital.cabinetoffice.gov.uk/2012/02/16/smart-answers-are-smart/) implements the selection mechanism as a form, it seems less crawlable… but perhaps they're not bothered). I'd like to have it so that the selection mechanism for the answers can be extended using another plugin.

Here's a mockup showing how I think of the selection meta box with just the basic multiple choice answers available:

![Decision Tree simple](https://f.cloud.github.com/assets/233434/179467/95866dda-7bff-11e2-8c22-368c15fef3dc.png)

In the model above, when you add an answer you are simultaneously adding a new child node and defining the answer text. If no title is provided, the answer text should be used for the title; however it should be possible for the text of the answer leading to a node to be separate from the title of that node.

I think re-parenting nodes will not be necessary.

Here's mockup showing how the selection meta box might work with some additional selection mechanisms enabled:

![Decision Tree metabox](https://f.cloud.github.com/assets/233434/176386/42617ccc-7b72-11e2-8aeb-c93bb750750d.png)

As an admin user, it would be useful to be able to navigate an entire decision tree while it is in draft, before it's published. This would require filtering permalinks to make them preview compatible.

It would be useful to be able to publish an entire decision tree in one action, rather than having to set the `post_status` on each node in turn.

**Display**

The answer links (or other selection mechanism) should be appended using `the_content` filter, and should have lots of lovely classes and IDs for CSS.

If no answer text has been provided, then the title of the child nodes should be used.

There should be no archive view for the Decision Trees CPT.

**Comment by simonwheatley** [comment]
**Display:** The previous answers should be displayed, as per the Gov.uk Smart Answers setup. This might present problems if one of the steps involves a more complex choice, like a postcode form.

---

Gov.uk Smart Answers has a URL structure constructed from the _answers_ you've given, rather than the node titles. This is particularly handy for passing state and/or constructing the "previous steps" in the tree when a user has got halfway through or has arrived halfway through from a tweeted link or similar. We can emulate this pretty easily for trees consisting entirely of nodes which only have answers which are simple choices. In this situation the rewrite rules can use the standard WordPress parent child relationships, which is nice and simple.

In steps where we must interpret the next node from a user input and a set of rules, e.g. if they've entered a postcode and we've queried an API to determine whether the next node is node F or node G, then we have an issue. We can still cache, as the node at the URL is only dependent on the URL, but for anyone landing on an uncached instance of that URL we may have one or more gnarly API or DB queries which could slow down the page somewhat. We could still do this, using two sets of rewrite rules for the Decision Tree post type: one standard parent/child hierarchy and one fallback rule, for when the simple rule doesn't apply, which traverses the tree and queries any APIs, etc, to assemble the page (which can then be cached).

**Comment by simonwheatley** [comment]
> As an admin user, it would be useful to be able to navigate an entire decision tree while it is in draft, before it's published. This would require filtering permalinks to make them preview compatible.
> 
> It would be useful to be able to publish an entire decision tree in one action, rather than having to set the post_status on each node in turn.

Create as a separate plugin, for reuse. Create as a public Github repo.

**Comment by johnbillion** [comment]
I think we can close this off.
