### ISSUE TITLE
Behaviour when deleting answers / nodes

### ISSUE THREAD

**Issue by johnbillion** [cftp/decision-trees#6]
Currently you cannot delete an individual answer from the editing screen. We need to decide on the desired behaviour.

When you delete an answer, should it also delete the answer node? If so, should this be recursive so all its answers and nodes are deleted too? 

cc simonwheatley

**Comment by johnbillion** [comment]
As discussed with @simonwheatley the plan is thus:
- Remove the 'Move to Trash' link from the DT node editing screen.
- Add a 'Trash' link to each node on the DT visualisation screen. When hovered over, this will highlight the current node and all descendants (in red or something) to indicate that the node and all its descendants will be trashed. Complete with a AYS message to confirm the trash action.
- Add a 'View Trashed Nodes' view to the visualisation screen. This will show trashed nodes in place with a visual difference (eg. paler colour). Add a 'Delete Permanently' link to each node, that when hovers highlights the current node and all its ancestors (as opposed to descendants) to indicate which nodes will be deleted. Complete with AYS on click.
- Add a 'Restore' link to each node that behaves the same as the 'Trash' link when hovered, highlighting all descendants.

Long term: Completely remove the main post listing screen so only the visualisation screen is available. Add a dropdown menu for switching between top-level nodes when more than one top-level node is present.

**Comment by simonwheatley** [comment]
Do we need the AYS messages?  

## 

My life in WordPress:
http://profiles.wordpress.org/users/simonwheatley/

Sweet Interaction Ltd is Registered in England/Wales, no. 6610741
Registered office: 7 Malton Av, Manchester, M21 8AT
