### ISSUE TITLE
Problems with class-answers-simple.php on line 25 WP 3.5.2 PHP 5-STABLE-STANDARD

### ISSUE THREAD

**Issue by odendahl** [cftp/decision-trees#8]
Just installed the plugin and when adding an answer to a node got a fatal error: Call to undefined function get_called_class() in /kunden/399092_47441/webseiten/wordpress/wp-content/plugins/decision-trees-master/class-answers-simple.php on line 25

Any ideas how to solve that?

Thanks in advance

Chris

**Comment by johnbillion** [comment]
The plugin requires PHP 5.3 (`get_called_class()` is a PHP 5.3+ function). Your server must be running PHP 5.2. Sorry we didn't put this in the plugin description.

**Comment by odendahl** [comment]
Thanks for your swift reply!
